version: "3.8"
services:
  webui:
    build:
      context: "./"
      dockerfile: ".docker/Dockerfile"
    image: webui-aria2
    restart: unless-stopped
    volumes:
      - ${DOWNLOAD_DIR_PATH}:/data/downloads
      - ${CONFIG_DIR_PATH}:/home/aria/.aria2
    ports:
      - ${ARIA2_PORT}:6800
      - ${WEBUI_PORT}:8080
